# Deployment
# tells k8s what to run and how many copies

apiVersion: apps/v1
kind: Deployment

metadata:
  name: petclinic-app # name of deployment inside k8s
  labels:
    app: petclinic-app # used to identify and group related objects

spec: # actual config of what we want
  replicas: 3

  selector:
    matchLabels:
      app: petclinic-app # deployment manages pods with this. must match with template

  template: # blueprint of each pod
    metadata:
      labels:
        app: petclinic-app # every pod gets this label. service uses this to find pods and send traffic

    spec:
      containers:
        - name: petclinic-app # name of container
          image: ekampetclinic.azurecr.io/petclinic:latest # docker image to pull from acr
          ports:
            - containerPort: 8080 # port springboot listens inside container

---

# service
# tells k8s how to expose app to internet

apiVersion: v1
kind: Service

metadata:
  name: petclinic-service # name of service inside k8s
  labels:
    app: petclinic-app

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080

  selector:
    app: petclinic-app
